/**
 * Etiquetas/íconos en español de cada tipo de operación del outbox, y de los
 * campos del payload — fuente única para "Pendientes de envío" (lista), la vista
 * de contenido (BG3) y la exportación. Antes vivían inline en pendientes.ts.
 */
export const TIPO_LABEL: Record<string, string> = {
  bitacora: 'Parte / incidente de bitácora',
  checklist_preuso: 'Pre-uso de vehículo',
  vehiculo_entrega: 'Entrega / recepción de vehículo',
  mantenimiento: 'Mantenimiento de vehículo',
  combustible: 'Combustible',
  mantenimiento_cierre: 'Cierre de mantenimiento',
  crear_ruta: 'Ruta creada',
  ruta_estado: 'Cambio de estado de ruta',
  ruta_agregar_parada: 'Parada agregada a ruta',
  ruta_cambiar_destino: 'Cambio de destino de ruta',
  parada_avanzar: 'Avance de parada',
  conduce_entrega: 'Entrega de conduce',
  conduce_recepcion: 'Recepción de conduce',
  conduce_simple: 'Conduce (entrega directa)',
  conduce_transportista: 'Conduce con transportista',
  conduce_externo: 'Conduce externo',
  conduce_estado_op: 'Cambio de estado de conduce',
  conduce_entregado: 'Conduce entregado',
  conduce_confirmar: 'Confirmación de conduce',
  conduce_vincular_parada: 'Conduce vinculado a parada',
  conduce_firmar_receptor: 'Firma de recepción de conduce',
  conduce_transf_aceptar: 'Aceptar transferencia de conduce',
  vehiculo_traspaso: 'Traspaso de vehículo',
  aviso_novedad_vehiculo: 'Novedad de vehículo',
  accidente_vehiculo: 'Accidente de vehículo',
  dano_vehiculo: 'Daño de vehículo',
  multa_conductor: 'Multa de conductor',
  mensaje_enviar: 'Mensaje enviado',
  tarea_app_iniciar: 'Inicio de tarea',
  tarea_app_completar: 'Tarea completada',
  cronograma_tarea_iniciar: 'Inicio de tarea de cronograma',
  cronograma_tarea_completar: 'Tarea de cronograma completada',
  tarea_enlazar: 'Enlace de tarea',
  rrhh_asignar_item: 'Asignación de item a empleado',
  rrhh_asignacion_estado: 'Cambio de asignación',
  cl_liberacion: 'Liberación de checklist',
  inv_entrada: 'Entrada de inventario',
  inv_devolucion_obra: 'Devolución de obra',
  inv_salida: 'Salida de inventario',
  inv_conteo: 'Conteo de inventario',
  devolucion_chofer: 'Devolución de chofer',
  compra_ferreteria: 'Compra en ferretería',
  entrada_ferreteria_confirmar: 'Confirmar entrada de ferretería',
  solicitud: 'Requisición de materiales',
  retiro_material: 'Retiro de material dañado',
  reporte: 'Reporte',
  reporte_semanal: 'Inspección de vehículo',
  documento_upload: 'Documento (cédula / licencia)',
  nota_guardar: 'Nota guardada',
  nota_checklist_set: 'Nota de checklist',
  obra_charla: 'Charla de seguridad',
  obra_nc: 'No conformidad',
  obra_incidente: 'Incidente en obra',
  obra_accion_hecha: 'Acción correctiva hecha',
  obra_nc_verificar: 'Verificación de no conformidad',
  obra_checklist: 'Checklist de obra',
  obra_cubicacion: 'Cubicación',
  obra_avance_tarea: 'Avance de tarea de obra',
  obra_prueba_campo: 'Prueba de campo',
  obra_mano_obra: 'Registro de mano de obra',
  obra_pedido_urgente: 'Pedido urgente',
};

export const TIPO_ICON: Record<string, string> = {
  bitacora: '📓',
  checklist_preuso: '📋',
  vehiculo_entrega: '🚚',
  mantenimiento: '🔧',
  combustible: '⛽',
  mantenimiento_cierre: '🔧',
  crear_ruta: '🗺️',
  ruta_estado: '🗺️',
  ruta_agregar_parada: '📍',
  ruta_cambiar_destino: '📍',
  parada_avanzar: '📍',
  conduce_entrega: '📦',
  conduce_recepcion: '📥',
  conduce_simple: '📦',
  conduce_transportista: '🚛',
  conduce_externo: '🚛',
  conduce_estado_op: '🔄',
  conduce_entregado: '📦',
  conduce_confirmar: '✅',
  conduce_vincular_parada: '🔗',
  conduce_firmar_receptor: '✍️',
  conduce_transf_aceptar: '↔️',
  vehiculo_traspaso: '🔁',
  aviso_novedad_vehiculo: '⚠️',
  accidente_vehiculo: '💥',
  dano_vehiculo: '🛠️',
  multa_conductor: '🚦',
  mensaje_enviar: '💬',
  tarea_app_iniciar: '▶️',
  tarea_app_completar: '✅',
  cronograma_tarea_iniciar: '▶️',
  cronograma_tarea_completar: '✅',
  tarea_enlazar: '🔗',
  rrhh_asignar_item: '🧑‍💼',
  rrhh_asignacion_estado: '🧑‍💼',
  cl_liberacion: '✅',
  inv_entrada: '📥',
  inv_devolucion_obra: '🏗️',
  inv_salida: '📤',
  inv_conteo: '🔢',
  devolucion_chofer: '↩️',
  compra_ferreteria: '🛒',
  entrada_ferreteria_confirmar: '📥',
  solicitud: '🛒',
  retiro_material: '🚮',
  reporte: '📝',
  reporte_semanal: '📊',
  documento_upload: '🪪',
  nota_guardar: '🗒️',
  nota_checklist_set: '🗒️',
  obra_charla: '🦺',
  obra_nc: '⚠️',
  obra_incidente: '🚨',
  obra_accion_hecha: '✅',
  obra_nc_verificar: '🔎',
  obra_checklist: '📋',
  obra_cubicacion: '📐',
  obra_avance_tarea: '📈',
  obra_prueba_campo: '🧪',
  obra_mano_obra: '👷',
  obra_pedido_urgente: '🛒',
};

export function tipoOpLabel(t: string): string {
  return TIPO_LABEL[t] ?? t;
}
export function tipoOpIcon(t: string): string {
  return TIPO_ICON[t] ?? '📄';
}

/** BG3 — etiquetas legibles de las claves del payload para la vista de contenido. */
export const CAMPO_LABEL: Record<string, string> = {
  proyecto_id: 'Obra',
  fecha: 'Fecha',
  tipo: 'Tipo',
  comentarios: 'Comentarios',
  personal_carpinteria: 'Personal de carpintería',
  personal_acero: 'Personal de acero',
  trabajadores_casa: 'Trabajadores de la casa',
  otro_personal: 'Otro personal',
  bloque_entrepiso: 'Bloque / entrepiso',
  ingeniero_responsable: 'Ingeniero responsable',
  hora_fin_trabajo: 'Hora fin de trabajo',
  llovio: '¿Llovió?',
  lluvia_detalle: 'Detalle de lluvia',
  horas_lluvia: 'Horas de lluvia',
  hubo_migracion: '¿Hubo migración?',
  migracion_obreros: 'Obreros migrados',
  sin_actividad: 'No se trabajó en obra',
  motivo_sin_actividad: 'Motivo (no se trabajó)',
  motivo_sin_actividad_detalle: 'Detalle del motivo',
  hubo_equipos: '¿Hubo equipos alquilados?',
  descripcion: 'Descripción',
  gravedad: 'Gravedad',
  tipo_incidente: 'Tipo de incidente',
  motivo_dano: 'Motivo del daño',
  motivo_dano_detalle: 'Detalle del daño',
  notas: 'Notas',
  cantidad: 'Cantidad',
  unidad: 'Unidad',
  actividad: 'Actividad',
  estructura: 'Estructura',
  bloque: 'Bloque',
  equipo: 'Equipo',
  uso: 'Uso',
  proveedor: 'Proveedor',
  dano_detalle: 'Detalle del daño',
  tipo_restriccion: 'Restricción',
  descripcion_otro: 'Descripción',
};

export function campoLabel(k: string): string {
  return CAMPO_LABEL[k] ?? k.replace(/_/g, ' ').replace(/^\w/, (c) => c.toUpperCase());
}
